config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events, only: [:new,:index,:show,:edit,:create,:destroy,:update] do
    resources :comments,only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  root to: 'events#index'
  resources :users, only: [:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :comment, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  has_one_attached :image

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, presence: true
  validates :overview, presence: true
  validates :prefecture_status, presence: true
  validates :start_time, presence: true
  validates :image, presence: true


  def favorited?(user)
   favorites.exists?(user_id: user.id)
  end

  enum prefecture_status:{
     "---":0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
     沖縄県:47
   }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: 'User'
  belongs_to :follower, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships, foreign_key: :following_id
  has_many :followings, through: :relationships, source: :follower

  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :follower_id
  has_many :followers, through: :reverse_of_relationships, source: :following

  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?
   
   

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:name])
  end
  
  def set_time_zone
    Time.zone = current_user.time_zone
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @event = Event.find(params[:event_id])
    @comment = current_user.comments.build(comment_params)
    @comment.event_id = @event.id
    if @comment.save
      flash[:announce] = "コメントしました"
      redirect_to request.referrer || root_path
    else
      flash[:danger] = "コメントを入力してください"
      redirect_to request.referrer || root_path
    end
  end


  def destroy
    @event = Event.find(params[:event_id])
    Comment.find(params[:id]).destroy
    flash[:announce] = "コメントを削除しました"
    redirect_to request.referrer || root_path
  end



  private

  def comment_params
    params.require(:comment).permit(:comment, :user_id, :event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :ensure_correct_user, only: [:edit, :update, :destry]

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
      if @event.save
        redirect_to event_path(@event.id)
        flash[:announce] = "投稿に成功しました"
      else
        flash[:danger] = "必要情報を入力してください"
        render :new
      end
  end

  def index
    @events = Event.all.page(params[:page]).per(12).order(created_at: :desc)
  end


  def show
    @event = Event.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to event_path(@event)
      flash[:announce] = "編集に成功しました"
    else
      flash[:danger] = "必要情報を入力してください"
      redirect_to edit_event_path(@event)
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
    flash[:announce] = "削除に成功しました"
  end

  private

  def event_params
    params.require(:event).permit(:name, :overview, :prefecture_status, :start_time, :user_id, :image)
  end


  def ensure_correct_user
    @event = Event.find(params[:id])
    @user = @event.user
    unless @user == current_user
      flash[:danger] = "他のユーザーの情報は編集できません。"
      redirect_to root_path
    end
  end

  def ensure_correct_user
    @event = Event.find(params[:id])
    @user = @event.user
    unless @user == current_user
      flash[:danger] = "他のユーザーの情報は編集できません。"
      redirect_to events_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
      @event = Event.find(params[:event_id])
      @favorite = current_user.favorites.new(event_id: @event.id)
      @favorite.save
      redirect_to request.referrer || root_path
  end

  def destroy
    @event = Event.find(params[:event_id])
    @favorite = current_user.favorites.find_by(event_id: @event.id)
    @favorite.destroy
    redirect_to request.referrer || root_path
  end
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController


  def create
    following = current_user.relationships.build(follower_id: params[:user_id])
    following.save
    redirect_to request.referrer || root_path
  end

  def destroy
    following = current_user.relationships.find_by(follower_id: params[:user_id])
    following.destroy
    redirect_to request.referrer || root_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]


  def show
    @user = User.find(params[:id])
    @events = @user.events.page(params[:page]).per(8).order(created_at: :desc)
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:announce] = "編集に成功しました"
      redirect_to user_path(@user.id)
    else
      flash[:danger] = "名前を入力してください"
      render :edit
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @users = @user.followings.page(params[:page])
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers.page(params[:page])
  end


  private

  def user_params
    params.require(:user).permit(:name, :introduction, :email)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      flash[:danger] = "他のユーザーの情報は編集できません。"
      redirect_to user_path(current_user)
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [event, comment], url: event_comments_path(event), local: false, html: {class: "needs-validation", novalidate: true}) do |f| %>
  <div class="form-group">
    <%= f.label :comment, class: "form-label" %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに", class: "form-control", required: true %>
    <div class="invalid-feedback">コメントを入力してください</div>
  </div>
  <%= f.submit "送信する", class: "btn btn-lg btn-primary float-right mt-3" %>
<% end %>

app/views/events/_index.html.erb
<% events.each do |event| %>
  <div class="col-md-3 my-3">
    <div class="card">
      <%= link_to event_path(event) do %>
        <%= image_tag event.image, class: "card-img-top img-fluid", style: "width: 100%; height: 230px; object-fit: cover;" %>
      <% end %>
      <div class="card-body">
        <h5 class="card-title"><%= event.name %></h5>
        <p class="card-text">
          <%= event.prefecture_status_i18n %>
        </p>
      </div>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="container-fluid">
  <div class="row justify-content-center align-items-center vh-100">
    <div class="col-lg-6">
      <div class="card">
        <div class="card-body">
          <h1 class="card-title text-center">お祭り編集</h1>

          <%= form_with model: @event, url: event_path, local: true do |form| %>


            <div class="form-group">
              <%= form.label :image, "画像" %>
              <%= form.file_field :image, accept: "image/*", class: "form-control-file" %>
            </div>

            <div class="form-group">
              <%= form.label :name, "名前" %>
              <%= form.text_field :name, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= form.label :prefecture_status, "開催地" %>
              <%= form.select :prefecture_status, options_for_select(Event.prefecture_statuses_i18n.invert, selected: @event.prefecture_status), {}, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= form.label :start_time, "日時" %>
              <%= form.datetime_select :start_time, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= form.label :overview, "特徴" %>
              <%= form.text_area :overview, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= form.submit "編集する", class: "btn btn-primary btn-block" %>
              <%= link_to '削除する', event_path, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-danger btn-block destroy_post_#{@event.id}"%>
            </div>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="container my-5">
  <div class="row my-5">
    <div class="col-md-2">
      <%= link_to 'イベント追加', new_event_path, class: 'btn btn-primary mb-3' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= month_calendar events: @events, partial: 'simple_calendar/month_calendar' do |date, events| %>
        <%= date.day %>
        <% events.each do |event| %>
          <div>
            <%= link_to event.name, event_path(event.id) %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="row my-5">
    <%= render 'events/index',events: @events %>
  </div>
  <%= paginate @events, theme: 'twitter-bootstrap-4' %>
</div>

app/views/events/new.html.erb
<div class="container-fluid">
  <div class="row justify-content-center align-items-center vh-100">
    <div class="col-lg-6">
      <div class="card">
        <div class="card-body">
          <h1 class="card-title text-center">お祭り追加</h1>

          <%= form_with(model: @event, local: true, html: {class: "needs-validation", novalidate: true}) do |form| %>

            <div class="form-group">
              <%= form.label :image, "画像" %>
              <%= form.file_field :image, accept: "image/*", class: "form-control-file" %>
            </div>

            <div class="form-group">
              <%= form.label :name, "名前" %>
              <%= form.text_field :name, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= form.label :prefecture_status, "開催地" %>
              <%= form.select :prefecture_status, options_for_select(Event.prefecture_statuses_i18n.invert, selected: @event.prefecture_status), {}, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= form.label :start_time, "日時" %>
              <%= form.datetime_select :start_time, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= form.label :overview, "特徴" %>
              <%= form.text_area :overview, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= form.submit "保存", class: "btn btn-primary btn-block" %>
            </div>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<style>
  .custom-margin {
    margin-bottom: 300px;
  }
</style>

<div class="container my-5">
  <h5>
    <%= link_to user_path(@event.user.id) do %>
      <%= @event.user.name %>
    <% end %>
    の投稿
  </h5>
  <div class="row">
    <div class="col-md-6">
      <%= image_tag @event.image, width: "100%" %>
    </div>

    <div class="col-md-5">
      <h3><strong><%= @event.name %></strong></h3>
      <h5 class="my-3">日時：　<%= @event.start_time.strftime("%m月%d日 %H:%M") %></h5>
      <h4 class ="mt-5"><strong>特徴</strong></h4>
      <p class="my-3">
        <%= @event.overview %>
      </p>
    </div>

    <div class="col-md-1">
      <h5><%= @event.prefecture_status_i18n %></h5>
      <h5 class="my-3"><%= render "favorites/btn", event: @event %></h5>
      <div class="custom-margin"></div>
      <% if @event.user == current_user %>
        <%= link_to "編集", edit_event_path(@event), class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

  <div class="row my-5">
    <div class="col-md-6">
      <div id="comments_area">
        <%= render "comments/form", event: @event, comment: @comment %>
      </div>
    </div>
    <div class="col-md-6 my-5">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>User</th>
            <th>Comment</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @event.comments.each do |comment| %>
          <tr>
            <td>
              <%= link_to user_path(comment.user) do %>
                <%= comment.user.name %>
              <% end %>
            </td>
            <td><%= comment.comment %></td>
            <td>
              <% if comment.user == current_user %>
                <%= link_to "削除", event_comment_path(@event, comment), method: :delete, data: { confirm: '本当に消しますか？' }, remote: true, class: "btn btn-danger float-right" %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/favorites/_btn.html.erb
<% if event.favorited?(current_user) %>
  <%= link_to event_favorites_path(event), method: :delete, remote: true do %>
    <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
    <%= event.favorites.count %>
  <% end %>
<% else %>
  <%= link_to event_favorites_path(event), method: :post, remote: true do %>
    <i class="fas fa-heart" aria-hidden="true"></i>
    <%= event.favorites.count %>
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-success" style="background-image: linear-gradient(to right, #ff0000, #ff5f6d);">
    <div class="container">
      <a class="navbar-brand ml-5" href="/">
        <%= image_tag "logo.png", size: "150x100" %>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to root_path, class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i> ホーム
              <% end %>
            </li>
            <li class="nav-item">
              <%=  link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                <i class="fas fa-user-circle"></i> マイページ
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i> ログアウト
              <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                <i class="fas fa-user-plus"></i> 新規登録
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-in-alt"></i> ログイン
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <% if flash[:announce] %>
    <div class="alert alert-success" role="alert">
      <%= flash[:announce] %>
    </div>
  <% end %>
  <% if flash[:danger] %>
    <div class="alert alert-danger" role="alert">
      <%= flash[:danger] %>
    </div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Festivision</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>名前</th>
      <th>フォロー</th>
      <th>フォロワー</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.followings.count %></td>
        <td><%= user.followers.count %></td>
        <td>
          <% if user != current_user %>
            <% if user.is_followed_by?(current_user) %>
              <%= link_to user_relationships_path(user.id), method: :delete, class: 'btn btn-danger' do %>
                フォロー解除
              <% end %>
            <% else %>
              <%= link_to user_relationships_path(user.id), method: :post, class: 'btn btn-primary' do %>
                フォロー
              <% end %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user.id), class: "user_#{user.id} btn btn-secondary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class="container-fluid">
  <div class="row justify-content-center align-items-center vh-100">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h1 class="card-title text-center">ユーザー情報編集</h1>

          <%= form_with model: @user, url: user_path, local: true do |form| %>

            <div class="form-group">
              <%= form.label :name, "名前" %>
              <%= form.text_field :name, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= form.label :introduction, "紹介文", class: "mt-5" %>
              <%= form.text_area :introduction, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= form.submit "編集する", class: "btn btn-primary btn-block" %>
            </div>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class ='container my-5'>
  <div class ='row'>
    <div class="col-md-12">
      <h1><%= @user.name %>のフォロワー一覧</h1>
      <% if @users.exists? %>
        <%= render 'users/index',user: @user ,users: @users %>
      <% else %>
        <p>ユーザーはいません</p>
      <% end %>
    </div>
  </div>
</div>
<%= paginate @users, theme: 'twitter-bootstrap-4' %>

app/views/users/followings.html.erb
<div class ='container my-5'>
  <div class ='row'>
    <div class="col-md-12">
      <h1><%= @user.name %>のフォロー一覧</h1>
      <% if @users.exists? %>
        <%= render 'users/index',user: @user ,users: @users %>
      <% else %>
        <p>ユーザーはいません</p>
      <% end %>
    </div>
  </div>
</div>
<%= paginate @users, theme: 'twitter-bootstrap-4' %>

app/views/users/show.html.erb
<div class="container my-5">
  <h1 class="text-center">マイページ</h1>

  <div class="row my-5">
    <div class="col-md-2"></div>
    <div class="col-md-8 my-5">
      <div class="card" style="background-color: #eaf6f6; height: 400px;">
        <div class="card-body d-flex flex-column align-items-center">
          <h2 class="card-title text-center"><%= @user.name %></h2>
          <h5 class="card-text mt-5">
            フォロー<%= link_to @user.followings.count, followings_user_path(@user) %>　　フォロワー<%= link_to @user.followers.count, followers_user_path(@user) %>
          </h5>
          <h5 class="card-text mt-5">紹介文</h5>
          <p class="card-text"><%= @user.introduction %></p>
          <div class="mt-auto">
            <% if @user != current_user %>
              <% if @user.is_followed_by?(current_user) %>
                <%= link_to user_relationships_path(@user), method: :delete do %>
                  <button class ="btn btn-danger">フォロー解除</button>
                <% end %>
              <% else %>
                <%= link_to user_relationships_path(@user), method: :post do %>
                  <button class ="btn btn-primary">フォロー</button>
                <% end %>
              <% end %>
            <% end %>
          </div>
          <div class="mt-auto">
            <% if @user == current_user %>
              <%= link_to "編集", edit_user_path(@user), class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-2"></div>
  </div>

  <h3 class="text-center"><%= @user.name %>の投稿一覧</h3>
  <div class="row my-5">
    <%= render 'events/index',events: @events %>
  </div>
  <%= paginate @events, theme: 'twitter-bootstrap-4' %>
</div>